
FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install tsparticles-preset-big-circles tsparticles-engine tsparticles-updater-tilt tsparticles-interaction-light

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]

